logger:
  logging-level: info
keywords:
  extractors:
  - language: en
    prunning: 10
    min-keyword-length: 3
    generate-title-when-missing: true
    title-max-length: 120
    resources-base-path: resources/modeling/tokenizer/en
    keywords-rules: keywords-rules.json
