logger:
  logging-level: info
pipeline:
  default-language: en
  configs:
    converter: converter.yaml
    tokenizer: tokenizer.yaml
    morphosyntax: mstagger.yaml
    ner: nertagger.yaml
    syntax: syntactic-tagger.yaml
    keywords: keywords.yaml
    chunking: golden-chunking.yaml
    ontology: document-ontology.yaml
    chunk-questions: chunk-questions.yaml
