logger:
  logging-level: info
syntax:
  taggers:
  - language: en
    resources-base-path: resources/modeling/tokenizer/en
    use-mwe: true
    mwe: tkeir_mwe.pkl
    syntactic-rules: syntactic-rules.json
