# -*- coding: utf-8 -*-
"""Convert source document to tkeir indexer document
Author: Eric Blaudez (Eric Blaudez)

Copyright (c) 2020 by THALES
"""

from thot.syntactictagger_svc import main
import os, signal
import unittest
import time
import requests
import json


service_pid = 0
dir_path = os.path.dirname(os.path.realpath(__file__))
test_file_path = os.path.abspath(os.path.join(dir_path, "../data/test-outputs-ner"))
ssl_verify = False


class TestSyntacticTaggerSvc(unittest.TestCase):
    @classmethod
    def setUpClass(self):
        global service_pid
        if service_pid == 0:
            service_pid = os.fork()
            if service_pid == 0:

                class args:
                    config = os.path.abspath(
                        os.path.join(
                            os.path.dirname(os.path.realpath(__file__)),
                            "../../../app/projects/default/configs/syntactic-tagger.json",
                        )
                    )

                print(args.config)
                main(args)
            else:
                load_finish = False
                count = 0
                while not load_finish:
                    try:
                        r = requests.get("https://localhost:10004/api/syntactictagger/health", verify=ssl_verify)
                        load_finish = r.status_code == 200
                    except:
                        count = count + 1
                        if count > 10:
                            load_finish = True
                            break
                        time.sleep(1)

    @classmethod
    def tearDownClass(self):
        if service_pid:
            os.kill(service_pid, signal.SIGINT)

    def test_health(self):
        if service_pid:
            r = requests.get("https://localhost:10004/api/syntactictagger/health", verify=ssl_verify)
            self.assertTrue(r.status_code == 200)

    def test_run(self):
        if service_pid:
            dir_path = os.path.dirname(os.path.realpath(__file__))
            data_path = os.path.abspath(os.path.join(dir_path, "../data/"))

            with open(os.path.join(test_file_path, "mail3.txt.converted.tokenized.ms.ner.json")) as f:
                tkeir_doc = json.load(f)
                f.close()
                r = requests.post("https://localhost:10004/api/syntactictagger/run", json=tkeir_doc, verify=ssl_verify)

            tkeir_doc = r.json()["results"]

            test = dict()
            test["title_deps"] = [
                {
                    "text": "Lackawanna",
                    "lemma": "Lackawanna",
                    "pos": "PROPN",
                    "head": 1,
                    "dep": "compound",
                    "lefts": [],
                    "rights": [],
                },
                {"text": "Letter", "lemma": "Letter", "pos": "PROPN", "head": 1, "dep": "ROOT", "lefts": [0], "rights": [2]},
                {"text": "of", "lemma": "of", "pos": "ADP", "head": 1, "dep": "prep", "lefts": [], "rights": [3]},
                {"text": "Credit", "lemma": "Credit", "pos": "PROPN", "head": 2, "dep": "pobj", "lefts": [], "rights": []},
            ]
            test["content_deps"] = [
                {"text": "Based", "lemma": "base", "pos": "VERB", "head": 8, "dep": "prep", "lefts": [], "rights": [1]},
                {"text": "on", "lemma": "on", "pos": "ADP", "head": 0, "dep": "prep", "lefts": [], "rights": [3]},
                {"text": "our", "lemma": "our", "pos": "PRON", "head": 3, "dep": "poss", "lefts": [], "rights": []},
                {
                    "text": "discussion",
                    "lemma": "discussion",
                    "pos": "NOUN",
                    "head": 1,
                    "dep": "pobj",
                    "lefts": [2],
                    "rights": [],
                },
                {"text": "last", "lemma": "last", "pos": "ADJ", "head": 5, "dep": "amod", "lefts": [], "rights": []},
                {"text": "week", "lemma": "week", "pos": "NOUN", "head": 8, "dep": "npadvmod", "lefts": [4], "rights": []},
                {"text": ",", "lemma": ",", "pos": "PUNCT", "head": 8, "dep": "punct", "lefts": [], "rights": []},
                {"text": "here", "lemma": "here", "pos": "ADV", "head": 8, "dep": "advmod", "lefts": [], "rights": []},
                {
                    "text": "is",
                    "lemma": "be",
                    "pos": "VERB",
                    "head": 8,
                    "dep": "ROOT",
                    "lefts": [0, 5, 6, 7],
                    "rights": [10, 17],
                },
                {"text": "some", "lemma": "some", "pos": "DET", "head": 10, "dep": "det", "lefts": [], "rights": []},
                {
                    "text": "information",
                    "lemma": "information",
                    "pos": "NOUN",
                    "head": 8,
                    "dep": "nsubj",
                    "lefts": [9],
                    "rights": [11],
                },
                {"text": "under", "lemma": "under", "pos": "ADP", "head": 10, "dep": "prep", "lefts": [], "rights": [14]},
                {"text": "the", "lemma": "the", "pos": "DET", "head": 14, "dep": "det", "lefts": [], "rights": []},
                {
                    "text": "Lackawanna",
                    "lemma": "Lackawanna",
                    "pos": "PROPN",
                    "head": 14,
                    "dep": "compound",
                    "lefts": [],
                    "rights": [],
                },
                {
                    "text": "letter",
                    "lemma": "letter",
                    "pos": "NOUN",
                    "head": 11,
                    "dep": "pobj",
                    "lefts": [12, 13],
                    "rights": [15],
                },
                {"text": "of", "lemma": "of", "pos": "ADP", "head": 14, "dep": "prep", "lefts": [], "rights": [16]},
                {"text": "credit", "lemma": "credit", "pos": "NOUN", "head": 15, "dep": "pobj", "lefts": [], "rights": []},
                {"text": ".", "lemma": ".", "pos": "PUNCT", "head": 8, "dep": "punct", "lefts": [], "rights": []},
                {"text": "Under", "lemma": "under", "pos": "ADP", "head": 28, "dep": "prep", "lefts": [], "rights": [20]},
                {"text": "the", "lemma": "the", "pos": "DET", "head": 20, "dep": "det", "lefts": [], "rights": []},
                {"text": "letter", "lemma": "letter", "pos": "NOUN", "head": 18, "dep": "pobj", "lefts": [19], "rights": [21]},
                {"text": "of", "lemma": "of", "pos": "ADP", "head": 20, "dep": "prep", "lefts": [], "rights": [22]},
                {"text": "credit", "lemma": "credit", "pos": "NOUN", "head": 21, "dep": "pobj", "lefts": [], "rights": []},
                {"text": ",", "lemma": ",", "pos": "PUNCT", "head": 28, "dep": "punct", "lefts": [], "rights": []},
                {"text": "the", "lemma": "the", "pos": "DET", "head": 26, "dep": "det", "lefts": [], "rights": []},
                {"text": "stated", "lemma": "state", "pos": "VERB", "head": 26, "dep": "amod", "lefts": [], "rights": []},
                {
                    "text": "amount",
                    "lemma": "amount",
                    "pos": "NOUN",
                    "head": 28,
                    "dep": "nsubjpass",
                    "lefts": [24, 25],
                    "rights": [],
                },
                {"text": "is", "lemma": "be", "pos": "VERB", "head": 28, "dep": "auxpass", "lefts": [], "rights": []},
                {
                    "text": "increased",
                    "lemma": "increase",
                    "pos": "VERB",
                    "head": 28,
                    "dep": "ROOT",
                    "lefts": [18, 23, 26, 27],
                    "rights": [31, 32, 43],
                },
                {"text": "$", "lemma": "$", "pos": "SYM", "head": 31, "dep": "quantmod", "lefts": [], "rights": []},
                {"text": "4.5", "lemma": "4.5", "pos": "NUM", "head": 31, "dep": "compound", "lefts": [], "rights": []},
                {
                    "text": "million",
                    "lemma": "million",
                    "pos": "NUM",
                    "head": 28,
                    "dep": "npadvmod",
                    "lefts": [29, 30],
                    "rights": [],
                },
                {"text": "upon", "lemma": "upon", "pos": "SCONJ", "head": 28, "dep": "prep", "lefts": [], "rights": [33]},
                {"text": "receipt", "lemma": "receipt", "pos": "NOUN", "head": 32, "dep": "pobj", "lefts": [], "rights": [34]},
                {"text": "from", "lemma": "from", "pos": "ADP", "head": 33, "dep": "prep", "lefts": [], "rights": [36]},
                {"text": "the", "lemma": "the", "pos": "DET", "head": 36, "dep": "det", "lefts": [], "rights": []},
                {
                    "text": "trustee",
                    "lemma": "trustee",
                    "pos": "NOUN",
                    "head": 34,
                    "dep": "pobj",
                    "lefts": [35],
                    "rights": [37],
                },
                {"text": "of", "lemma": "of", "pos": "ADP", "head": 36, "dep": "prep", "lefts": [], "rights": [38]},
                {
                    "text": "notification",
                    "lemma": "notification",
                    "pos": "NOUN",
                    "head": 37,
                    "dep": "pobj",
                    "lefts": [],
                    "rights": [39],
                },
                {"text": "of", "lemma": "of", "pos": "ADP", "head": 38, "dep": "prep", "lefts": [], "rights": [42]},
                {"text": "the", "lemma": "the", "pos": "DET", "head": 42, "dep": "det", "lefts": [], "rights": []},
                {
                    "text": "Completion",
                    "lemma": "Completion",
                    "pos": "PROPN",
                    "head": 42,
                    "dep": "compound",
                    "lefts": [],
                    "rights": [],
                },
                {"text": "Date", "lemma": "Date", "pos": "PROPN", "head": 39, "dep": "pobj", "lefts": [40, 41], "rights": []},
                {"text": ".", "lemma": ".", "pos": "PUNCT", "head": 28, "dep": "punct", "lefts": [], "rights": []},
                {
                    "text": "Completion",
                    "lemma": "completion",
                    "pos": "NOUN",
                    "head": 45,
                    "dep": "compound",
                    "lefts": [],
                    "rights": [],
                },
                {"text": "Date", "lemma": "Date", "pos": "PROPN", "head": 47, "dep": "nsubjpass", "lefts": [44], "rights": []},
                {"text": "is", "lemma": "be", "pos": "VERB", "head": 47, "dep": "auxpass", "lefts": [], "rights": []},
                {
                    "text": "defined",
                    "lemma": "define",
                    "pos": "VERB",
                    "head": 47,
                    "dep": "ROOT",
                    "lefts": [45, 46],
                    "rights": [48, 51, 55],
                },
                {"text": "in", "lemma": "in", "pos": "ADP", "head": 47, "dep": "prep", "lefts": [], "rights": [50]},
                {"text": "the", "lemma": "the", "pos": "DET", "head": 50, "dep": "det", "lefts": [], "rights": []},
                {"text": "LC", "lemma": "LC", "pos": "PROPN", "head": 48, "dep": "pobj", "lefts": [49], "rights": []},
                {"text": "as", "lemma": "as", "pos": "ADP", "head": 47, "dep": "prep", "lefts": [], "rights": [52]},
                {"text": "in", "lemma": "in", "pos": "ADP", "head": 51, "dep": "prep", "lefts": [], "rights": [54]},
                {"text": "the", "lemma": "the", "pos": "DET", "head": 54, "dep": "det", "lefts": [], "rights": []},
                {
                    "text": "Indenture",
                    "lemma": "Indenture",
                    "pos": "PROPN",
                    "head": 52,
                    "dep": "pobj",
                    "lefts": [53],
                    "rights": [],
                },
                {"text": ".", "lemma": ".", "pos": "PUNCT", "head": 47, "dep": "punct", "lefts": [], "rights": []},
                {"text": "However", "lemma": "however", "pos": "ADV", "head": 60, "dep": "advmod", "lefts": [], "rights": []},
                {"text": ",", "lemma": ",", "pos": "PUNCT", "head": 60, "dep": "punct", "lefts": [], "rights": []},
                {"text": "this", "lemma": "this", "pos": "DET", "head": 59, "dep": "det", "lefts": [], "rights": []},
                {
                    "text": "definition",
                    "lemma": "definition",
                    "pos": "NOUN",
                    "head": 60,
                    "dep": "nsubj",
                    "lefts": [58],
                    "rights": [],
                },
                {
                    "text": "is",
                    "lemma": "be",
                    "pos": "VERB",
                    "head": 60,
                    "dep": "ROOT",
                    "lefts": [56, 57, 59],
                    "rights": [63, 71],
                },
                {"text": "exactly", "lemma": "exactly", "pos": "ADV", "head": 63, "dep": "advmod", "lefts": [], "rights": []},
                {"text": "the", "lemma": "the", "pos": "DET", "head": 63, "dep": "det", "lefts": [], "rights": []},
                {"text": "same", "lemma": "same", "pos": "ADJ", "head": 60, "dep": "attr", "lefts": [61, 62], "rights": [65]},
                {"text": "as", "lemma": "as", "pos": "ADP", "head": 65, "dep": "mark", "lefts": [], "rights": []},
                {"text": "used", "lemma": "use", "pos": "VERB", "head": 63, "dep": "advcl", "lefts": [64], "rights": [66]},
                {"text": "in", "lemma": "in", "pos": "ADP", "head": 65, "dep": "prep", "lefts": [], "rights": [70]},
                {"text": "the", "lemma": "the", "pos": "DET", "head": 70, "dep": "det", "lefts": [], "rights": []},
                {
                    "text": "subordinated",
                    "lemma": "subordinated",
                    "pos": "ADJ",
                    "head": 70,
                    "dep": "amod",
                    "lefts": [],
                    "rights": [],
                },
                {"text": "loan", "lemma": "loan", "pos": "NOUN", "head": 70, "dep": "compound", "lefts": [], "rights": []},
                {
                    "text": "agreement",
                    "lemma": "agreement",
                    "pos": "NOUN",
                    "head": 66,
                    "dep": "pobj",
                    "lefts": [67, 68, 69],
                    "rights": [],
                },
                {"text": ".", "lemma": ".", "pos": "PUNCT", "head": 60, "dep": "punct", "lefts": [], "rights": []},
                {"text": "I", "lemma": "I", "pos": "PRON", "head": 74, "dep": "nsubj", "lefts": [], "rights": []},
                {"text": "have", "lemma": "have", "pos": "VERB", "head": 74, "dep": "aux", "lefts": [], "rights": []},
                {
                    "text": "attached",
                    "lemma": "attach",
                    "pos": "VERB",
                    "head": 74,
                    "dep": "ROOT",
                    "lefts": [72, 73],
                    "rights": [76, 88],
                },
                {"text": "my", "lemma": "my", "pos": "PRON", "head": 76, "dep": "poss", "lefts": [], "rights": []},
                {
                    "text": "analysis",
                    "lemma": "analysis",
                    "pos": "NOUN",
                    "head": 74,
                    "dep": "dobj",
                    "lefts": [75],
                    "rights": [77],
                },
                {"text": "of", "lemma": "of", "pos": "ADP", "head": 76, "dep": "prep", "lefts": [], "rights": [79]},
                {"text": "the", "lemma": "the", "pos": "DET", "head": 79, "dep": "det", "lefts": [], "rights": []},
                {
                    "text": "requirements",
                    "lemma": "requirement",
                    "pos": "NOUN",
                    "head": 77,
                    "dep": "pobj",
                    "lefts": [78],
                    "rights": [80],
                },
                {"text": "for", "lemma": "for", "pos": "ADP", "head": 79, "dep": "prep", "lefts": [], "rights": [83]},
                {"text": "the", "lemma": "the", "pos": "DET", "head": 83, "dep": "det", "lefts": [], "rights": []},
                {
                    "text": "Completion",
                    "lemma": "Completion",
                    "pos": "PROPN",
                    "head": 83,
                    "dep": "compound",
                    "lefts": [],
                    "rights": [],
                },
                {"text": "Date", "lemma": "Date", "pos": "PROPN", "head": 80, "dep": "pobj", "lefts": [81, 82], "rights": [84]},
                {"text": "under", "lemma": "under", "pos": "ADP", "head": 83, "dep": "prep", "lefts": [], "rights": [87]},
                {"text": "the", "lemma": "the", "pos": "DET", "head": 87, "dep": "det", "lefts": [], "rights": []},
                {"text": "Loan", "lemma": "Loan", "pos": "PROPN", "head": 87, "dep": "compound", "lefts": [], "rights": []},
                {
                    "text": "Agreement",
                    "lemma": "Agreement",
                    "pos": "PROPN",
                    "head": 84,
                    "dep": "pobj",
                    "lefts": [85, 86],
                    "rights": [],
                },
                {"text": ".", "lemma": ".", "pos": "PUNCT", "head": 74, "dep": "punct", "lefts": [], "rights": []},
                {
                    "text": "Completion",
                    "lemma": "completion",
                    "pos": "NOUN",
                    "head": 90,
                    "dep": "nsubj",
                    "lefts": [],
                    "rights": [],
                },
                {
                    "text": "requires",
                    "lemma": "require",
                    "pos": "VERB",
                    "head": 90,
                    "dep": "ROOT",
                    "lefts": [89],
                    "rights": [91, 92, 97, 112],
                },
                {"text": ",", "lemma": ",", "pos": "PUNCT", "head": 90, "dep": "punct", "lefts": [], "rights": []},
                {"text": "among", "lemma": "among", "pos": "ADP", "head": 90, "dep": "prep", "lefts": [], "rights": [94]},
                {"text": "other", "lemma": "other", "pos": "ADJ", "head": 94, "dep": "amod", "lefts": [], "rights": []},
                {"text": "things", "lemma": "thing", "pos": "NOUN", "head": 92, "dep": "pobj", "lefts": [93], "rights": []},
                {"text": ",", "lemma": ",", "pos": "PUNCT", "head": 97, "dep": "punct", "lefts": [], "rights": []},
                {"text": "the", "lemma": "the", "pos": "DET", "head": 97, "dep": "det", "lefts": [], "rights": []},
                {
                    "text": "production",
                    "lemma": "production",
                    "pos": "NOUN",
                    "head": 90,
                    "dep": "dep",
                    "lefts": [95, 96],
                    "rights": [98],
                },
                {"text": "within", "lemma": "within", "pos": "ADP", "head": 97, "dep": "prep", "lefts": [], "rights": [102]},
                {"text": "a", "lemma": "a", "pos": "DET", "head": 102, "dep": "det", "lefts": [], "rights": []},
                {"text": "24", "lemma": "24", "pos": "NUM", "head": 101, "dep": "nummod", "lefts": [], "rights": []},
                {"text": "day", "lemma": "day", "pos": "NOUN", "head": 102, "dep": "compound", "lefts": [100], "rights": []},
                {
                    "text": "period",
                    "lemma": "period",
                    "pos": "NOUN",
                    "head": 98,
                    "dep": "pobj",
                    "lefts": [99, 101],
                    "rights": [103],
                },
                {"text": "of", "lemma": "of", "pos": "ADP", "head": 102, "dep": "prep", "lefts": [], "rights": [107]},
                {"text": "3", "lemma": "3", "pos": "NUM", "head": 106, "dep": "quantmod", "lefts": [], "rights": []},
                {"text": ",", "lemma": ",", "pos": "PUNCT", "head": 106, "dep": "punct", "lefts": [], "rights": []},
                {"text": "000", "lemma": "000", "pos": "NUM", "head": 107, "dep": "nummod", "lefts": [104, 105], "rights": []},
                {"text": "units", "lemma": "unit", "pos": "NOUN", "head": 103, "dep": "pobj", "lefts": [106], "rights": [108]},
                {"text": "with", "lemma": "with", "pos": "ADP", "head": 107, "dep": "prep", "lefts": [], "rights": [111]},
                {"text": "certain", "lemma": "certain", "pos": "ADJ", "head": 111, "dep": "amod", "lefts": [], "rights": []},
                {
                    "text": "quality",
                    "lemma": "quality",
                    "pos": "NOUN",
                    "head": 111,
                    "dep": "compound",
                    "lefts": [],
                    "rights": [],
                },
                {
                    "text": "specifications",
                    "lemma": "specification",
                    "pos": "NOUN",
                    "head": 108,
                    "dep": "pobj",
                    "lefts": [109, 110],
                    "rights": [],
                },
                {"text": ".", "lemma": ".", "pos": "PUNCT", "head": 90, "dep": "punct", "lefts": [], "rights": []},
                {
                    "text": "Approval",
                    "lemma": "approval",
                    "pos": "NOUN",
                    "head": 119,
                    "dep": "nsubjpass",
                    "lefts": [],
                    "rights": [114],
                },
                {"text": "of", "lemma": "of", "pos": "ADP", "head": 113, "dep": "prep", "lefts": [], "rights": [116]},
                {"text": "these", "lemma": "these", "pos": "DET", "head": 116, "dep": "det", "lefts": [], "rights": []},
                {
                    "text": "specifications",
                    "lemma": "specification",
                    "pos": "NOUN",
                    "head": 114,
                    "dep": "pobj",
                    "lefts": [115],
                    "rights": [],
                },
                {"text": "must", "lemma": "must", "pos": "AUX", "head": 119, "dep": "aux", "lefts": [], "rights": []},
                {"text": "be", "lemma": "be", "pos": "VERB", "head": 119, "dep": "auxpass", "lefts": [], "rights": []},
                {
                    "text": "made",
                    "lemma": "make",
                    "pos": "VERB",
                    "head": 119,
                    "dep": "ROOT",
                    "lefts": [113, 117, 118],
                    "rights": [120, 124],
                },
                {"text": "by", "lemma": "by", "pos": "ADP", "head": 119, "dep": "agent", "lefts": [], "rights": [123]},
                {"text": "the", "lemma": "the", "pos": "DET", "head": 123, "dep": "det", "lefts": [], "rights": []},
                {
                    "text": "independent",
                    "lemma": "independent",
                    "pos": "ADJ",
                    "head": 123,
                    "dep": "amod",
                    "lefts": [],
                    "rights": [],
                },
                {
                    "text": "engineer",
                    "lemma": "engineer",
                    "pos": "NOUN",
                    "head": 120,
                    "dep": "pobj",
                    "lefts": [121, 122],
                    "rights": [],
                },
                {"text": ".", "lemma": ".", "pos": "PUNCT", "head": 119, "dep": "punct", "lefts": [], "rights": []},
                {"text": "To", "lemma": "to", "pos": "ADP", "head": 130, "dep": "prep", "lefts": [], "rights": [126]},
                {"text": "date", "lemma": "date", "pos": "NOUN", "head": 125, "dep": "pobj", "lefts": [], "rights": []},
                {"text": ",", "lemma": ",", "pos": "PUNCT", "head": 130, "dep": "punct", "lefts": [], "rights": []},
                {"text": "we", "lemma": "we", "pos": "PRON", "head": 130, "dep": "nsubj", "lefts": [], "rights": []},
                {"text": "have", "lemma": "have", "pos": "VERB", "head": 130, "dep": "aux", "lefts": [], "rights": []},
                {
                    "text": "taken",
                    "lemma": "take",
                    "pos": "VERB",
                    "head": 130,
                    "dep": "ROOT",
                    "lefts": [125, 127, 128, 129],
                    "rights": [132, 133, 134, 138],
                },
                {"text": "a", "lemma": "a", "pos": "DET", "head": 132, "dep": "det", "lefts": [], "rights": []},
                {"text": "wait", "lemma": "wait", "pos": "NOUN", "head": 130, "dep": "dobj", "lefts": [131], "rights": []},
                {"text": "and", "lemma": "and", "pos": "CCONJ", "head": 130, "dep": "cc", "lefts": [], "rights": []},
                {"text": "see", "lemma": "see", "pos": "VERB", "head": 130, "dep": "conj", "lefts": [], "rights": [135, 136]},
                {"text": "approach", "lemma": "approach", "pos": "NOUN", "head": 134, "dep": "dobj", "lefts": [], "rights": []},
                {
                    "text": "regarding",
                    "lemma": "regard",
                    "pos": "VERB",
                    "head": 134,
                    "dep": "prep",
                    "lefts": [],
                    "rights": [137],
                },
                {
                    "text": "completion",
                    "lemma": "completion",
                    "pos": "NOUN",
                    "head": 136,
                    "dep": "pobj",
                    "lefts": [],
                    "rights": [],
                },
                {"text": ".", "lemma": ".", "pos": "PUNCT", "head": 130, "dep": "punct", "lefts": [], "rights": []},
                {"text": "Please", "lemma": "please", "pos": "INTJ", "head": 140, "dep": "intj", "lefts": [], "rights": []},
                {
                    "text": "review",
                    "lemma": "review",
                    "pos": "VERB",
                    "head": 140,
                    "dep": "ROOT",
                    "lefts": [139],
                    "rights": [141, 142, 150],
                },
                {"text": "and", "lemma": "and", "pos": "CCONJ", "head": 140, "dep": "cc", "lefts": [], "rights": []},
                {"text": "advise", "lemma": "advise", "pos": "VERB", "head": 140, "dep": "conj", "lefts": [], "rights": [143]},
                {"text": "on", "lemma": "on", "pos": "ADP", "head": 142, "dep": "prep", "lefts": [], "rights": [145]},
                {"text": "your", "lemma": "your", "pos": "PRON", "head": 145, "dep": "poss", "lefts": [], "rights": []},
                {
                    "text": "thoughts",
                    "lemma": "thought",
                    "pos": "NOUN",
                    "head": 143,
                    "dep": "pobj",
                    "lefts": [144],
                    "rights": [146],
                },
                {"text": "on", "lemma": "on", "pos": "ADP", "head": 145, "dep": "prep", "lefts": [], "rights": [147]},
                {
                    "text": "strategy",
                    "lemma": "strategy",
                    "pos": "NOUN",
                    "head": 146,
                    "dep": "pobj",
                    "lefts": [],
                    "rights": [148],
                },
                {"text": "going", "lemma": "go", "pos": "VERB", "head": 147, "dep": "acl", "lefts": [], "rights": [149]},
                {"text": "forward", "lemma": "forward", "pos": "ADV", "head": 148, "dep": "advmod", "lefts": [], "rights": []},
                {"text": ".", "lemma": ".", "pos": "PUNCT", "head": 140, "dep": "punct", "lefts": [], "rights": []},
                {
                    "text": "Obviously",
                    "lemma": "obviously",
                    "pos": "ADV",
                    "head": 154,
                    "dep": "advmod",
                    "lefts": [],
                    "rights": [],
                },
                {"text": ",", "lemma": ",", "pos": "PUNCT", "head": 154, "dep": "punct", "lefts": [], "rights": []},
                {"text": "we", "lemma": "we", "pos": "PRON", "head": 154, "dep": "nsubj", "lefts": [], "rights": []},
                {
                    "text": "want",
                    "lemma": "want",
                    "pos": "VERB",
                    "head": 154,
                    "dep": "ROOT",
                    "lefts": [151, 152, 153],
                    "rights": [156, 164],
                },
                {"text": "to", "lemma": "to", "pos": "PART", "head": 156, "dep": "aux", "lefts": [], "rights": []},
                {
                    "text": "hold",
                    "lemma": "hold",
                    "pos": "VERB",
                    "head": 154,
                    "dep": "xcomp",
                    "lefts": [155],
                    "rights": [157, 158],
                },
                {"text": "them", "lemma": "they", "pos": "PRON", "head": 156, "dep": "dobj", "lefts": [], "rights": []},
                {"text": "to", "lemma": "to", "pos": "ADP", "head": 156, "dep": "prep", "lefts": [], "rights": [160]},
                {"text": "the", "lemma": "the", "pos": "DET", "head": 160, "dep": "det", "lefts": [], "rights": []},
                {
                    "text": "letter",
                    "lemma": "letter",
                    "pos": "NOUN",
                    "head": 158,
                    "dep": "pobj",
                    "lefts": [159],
                    "rights": [161],
                },
                {"text": "of", "lemma": "of", "pos": "ADP", "head": 160, "dep": "prep", "lefts": [], "rights": [163]},
                {"text": "the", "lemma": "the", "pos": "DET", "head": 163, "dep": "det", "lefts": [], "rights": []},
                {
                    "text": "agreement",
                    "lemma": "agreement",
                    "pos": "NOUN",
                    "head": 161,
                    "dep": "pobj",
                    "lefts": [162],
                    "rights": [],
                },
                {"text": ".", "lemma": ".", "pos": "PUNCT", "head": 154, "dep": "punct", "lefts": [], "rights": []},
                {"text": "The", "lemma": "the", "pos": "DET", "head": 166, "dep": "det", "lefts": [], "rights": []},
                {"text": "LC", "lemma": "LC", "pos": "PROPN", "head": 167, "dep": "nsubj", "lefts": [165], "rights": []},
                {
                    "text": "expires",
                    "lemma": "expire",
                    "pos": "VERB",
                    "head": 167,
                    "dep": "ROOT",
                    "lefts": [166],
                    "rights": [168, 171, 175],
                },
                {"text": "on", "lemma": "on", "pos": "ADP", "head": 167, "dep": "prep", "lefts": [], "rights": [169]},
                {"text": "June", "lemma": "June", "pos": "PROPN", "head": 168, "dep": "pobj", "lefts": [], "rights": [170]},
                {"text": "30", "lemma": "30", "pos": "NUM", "head": 169, "dep": "nummod", "lefts": [], "rights": []},
                {"text": "and", "lemma": "and", "pos": "CCONJ", "head": 167, "dep": "cc", "lefts": [], "rights": []},
                {"text": "it", "lemma": "it", "pos": "PRON", "head": 175, "dep": "nsubj", "lefts": [], "rights": []},
                {"text": "does", "lemma": "do", "pos": "VERB", "head": 175, "dep": "aux", "lefts": [], "rights": []},
                {"text": "not", "lemma": "not", "pos": "PART", "head": 175, "dep": "neg", "lefts": [], "rights": []},
                {
                    "text": "appear",
                    "lemma": "appear",
                    "pos": "VERB",
                    "head": 167,
                    "dep": "conj",
                    "lefts": [172, 173, 174],
                    "rights": [176, 195],
                },
                {"text": "that", "lemma": "that", "pos": "SCONJ", "head": 175, "dep": "dobj", "lefts": [], "rights": [177]},
                {"text": "under", "lemma": "under", "pos": "ADP", "head": 176, "dep": "prep", "lefts": [], "rights": [180]},
                {"text": "the", "lemma": "the", "pos": "DET", "head": 180, "dep": "det", "lefts": [], "rights": []},
                {"text": "loan", "lemma": "loan", "pos": "NOUN", "head": 180, "dep": "compound", "lefts": [], "rights": []},
                {
                    "text": "agreement",
                    "lemma": "agreement",
                    "pos": "NOUN",
                    "head": 177,
                    "dep": "pobj",
                    "lefts": [178, 179],
                    "rights": [184],
                },
                {"text": "that", "lemma": "that", "pos": "DET", "head": 186, "dep": "dobj", "lefts": [], "rights": []},
                {"text": "we", "lemma": "we", "pos": "PRON", "head": 184, "dep": "nsubjpass", "lefts": [], "rights": []},
                {"text": "are", "lemma": "be", "pos": "VERB", "head": 184, "dep": "auxpass", "lefts": [], "rights": []},
                {
                    "text": "required",
                    "lemma": "require",
                    "pos": "VERB",
                    "head": 180,
                    "dep": "relcl",
                    "lefts": [182, 183],
                    "rights": [186],
                },
                {"text": "to", "lemma": "to", "pos": "PART", "head": 186, "dep": "aux", "lefts": [], "rights": []},
                {
                    "text": "fund",
                    "lemma": "fund",
                    "pos": "VERB",
                    "head": 184,
                    "dep": "xcomp",
                    "lefts": [181, 185],
                    "rights": [187],
                },
                {"text": "after", "lemma": "after", "pos": "ADP", "head": 186, "dep": "prep", "lefts": [], "rights": [189]},
                {"text": "the", "lemma": "the", "pos": "DET", "head": 189, "dep": "det", "lefts": [], "rights": []},
                {
                    "text": "expiration",
                    "lemma": "expiration",
                    "pos": "NOUN",
                    "head": 187,
                    "dep": "pobj",
                    "lefts": [188],
                    "rights": [190],
                },
                {"text": "of", "lemma": "of", "pos": "ADP", "head": 189, "dep": "prep", "lefts": [], "rights": [192]},
                {"text": "the", "lemma": "the", "pos": "DET", "head": 192, "dep": "det", "lefts": [], "rights": []},
                {
                    "text": "letter",
                    "lemma": "letter",
                    "pos": "NOUN",
                    "head": 190,
                    "dep": "pobj",
                    "lefts": [191],
                    "rights": [193],
                },
                {"text": "of", "lemma": "of", "pos": "ADP", "head": 192, "dep": "prep", "lefts": [], "rights": [194]},
                {"text": "credit", "lemma": "credit", "pos": "NOUN", "head": 193, "dep": "pobj", "lefts": [], "rights": []},
                {"text": ".", "lemma": ".", "pos": "PUNCT", "head": 175, "dep": "punct", "lefts": [], "rights": []},
                {"text": "If", "lemma": "if", "pos": "SCONJ", "head": 198, "dep": "mark", "lefts": [], "rights": []},
                {"text": "you", "lemma": "you", "pos": "PRON", "head": 198, "dep": "nsubj", "lefts": [], "rights": []},
                {
                    "text": "need",
                    "lemma": "need",
                    "pos": "VERB",
                    "head": 204,
                    "dep": "advcl",
                    "lefts": [196, 197],
                    "rights": [201],
                },
                {"text": "the", "lemma": "the", "pos": "DET", "head": 201, "dep": "det", "lefts": [], "rights": []},
                {
                    "text": "pertinent",
                    "lemma": "pertinent",
                    "pos": "ADJ",
                    "head": 201,
                    "dep": "amod",
                    "lefts": [],
                    "rights": [],
                },
                {
                    "text": "documents",
                    "lemma": "document",
                    "pos": "NOUN",
                    "head": 198,
                    "dep": "dobj",
                    "lefts": [199, 200],
                    "rights": [],
                },
                {"text": ",", "lemma": ",", "pos": "PUNCT", "head": 204, "dep": "punct", "lefts": [], "rights": []},
                {"text": "I", "lemma": "I", "pos": "PRON", "head": 204, "dep": "nsubj", "lefts": [], "rights": []},
                {
                    "text": "have",
                    "lemma": "have",
                    "pos": "VERB",
                    "head": 204,
                    "dep": "ROOT",
                    "lefts": [198, 202, 203],
                    "rights": [205, 206, 209],
                },
                {"text": "them", "lemma": "they", "pos": "PRON", "head": 204, "dep": "dobj", "lefts": [], "rights": []},
                {"text": "in", "lemma": "in", "pos": "ADP", "head": 204, "dep": "prep", "lefts": [], "rights": [208]},
                {"text": "my", "lemma": "my", "pos": "PRON", "head": 208, "dep": "poss", "lefts": [], "rights": []},
                {"text": "office", "lemma": "office", "pos": "NOUN", "head": 206, "dep": "pobj", "lefts": [207], "rights": []},
                {"text": ".", "lemma": ".", "pos": "PUNCT", "head": 204, "dep": "punct", "lefts": [], "rights": []},
                {"text": ".", "lemma": ".", "pos": "PUNCT", "head": 210, "dep": "ROOT", "lefts": [], "rights": []},
            ]
            test["kg"] = [
                {
                    "automatically_fill": True,
                    "confidence": 1.0,
                    "field_type": "mail-header",
                    "property": {
                        "content": "rel:instanceof",
                        "label_content": "",
                        "lemma_content": "rel:instanceof",
                        "positions": [-1],
                    },
                    "subject": {
                        "content": "john.enerson@enron.com",
                        "label_content": "",
                        "lemma_content": "john.enerson@enron.com",
                        "positions": [-1],
                    },
                    "value": {"content": "email", "label_content": "", "lemma_content": "email", "positions": [-1]},
                    "weight": 0.0,
                },
                {
                    "automatically_fill": True,
                    "confidence": 1.0,
                    "field_type": "mail-header",
                    "property": {
                        "content": "rel:instanceof",
                        "label_content": "",
                        "lemma_content": "rel:instanceof",
                        "positions": [-1],
                    },
                    "subject": {
                        "content": "John Enerso",
                        "label_content": "",
                        "lemma_content": "John Enerso",
                        "positions": [-1],
                    },
                    "value": {"content": "person", "label_content": "", "lemma_content": "person", "positions": [-1]},
                    "weight": 0.0,
                },
                {
                    "automatically_fill": True,
                    "confidence": 1.0,
                    "field_type": "mail-header",
                    "property": {
                        "content": "rel:mailto",
                        "label_content": "",
                        "lemma_content": "rel:mailto",
                        "positions": [-1],
                    },
                    "subject": {
                        "content": "john.enerson@enron.com",
                        "label_content": "",
                        "lemma_content": "john.enerson@enron.com",
                        "positions": [-1],
                    },
                    "value": {
                        "content": "richard.sanders@enron.com",
                        "label_content": "",
                        "lemma_content": "richard.sanders@enron.com",
                        "positions": [-1],
                    },
                    "weight": 0.0,
                },
                {
                    "automatically_fill": True,
                    "confidence": 1.0,
                    "field_type": "mail-header",
                    "property": {
                        "content": "rel:mailto",
                        "label_content": "",
                        "lemma_content": "rel:mailto",
                        "positions": [-1],
                    },
                    "subject": {
                        "content": "John Enerso",
                        "label_content": "",
                        "lemma_content": "John Enerso",
                        "positions": [-1],
                    },
                    "value": {
                        "content": "Richard B Sander",
                        "label_content": "",
                        "lemma_content": "Richard B Sander",
                        "positions": [-1],
                    },
                    "weight": 0.0,
                },
                {
                    "automatically_fill": True,
                    "confidence": 1.0,
                    "field_type": "mail-header",
                    "property": {
                        "content": "rel:instanceof",
                        "label_content": "",
                        "lemma_content": "rel:instanceof",
                        "positions": [-1],
                    },
                    "subject": {
                        "content": "Richard B Sander",
                        "label_content": "",
                        "lemma_content": "Richard B Sander",
                        "positions": [-1],
                    },
                    "value": {"content": "person", "label_content": "", "lemma_content": "person", "positions": [-1]},
                    "weight": 0.0,
                },
                {
                    "automatically_fill": True,
                    "confidence": 1.0,
                    "field_type": "mail-header",
                    "property": {
                        "content": "rel:mailcc",
                        "label_content": "",
                        "lemma_content": "rel:mailcc",
                        "positions": [-1],
                    },
                    "subject": {
                        "content": "john.enerson@enron.com",
                        "label_content": "",
                        "lemma_content": "john.enerson@enron.com",
                        "positions": [-1],
                    },
                    "value": {
                        "content": "richard.lydecker@enron.com",
                        "label_content": "",
                        "lemma_content": "richard.lydecker@enron.com",
                        "positions": [-1],
                    },
                    "weight": 0.0,
                },
                {
                    "automatically_fill": True,
                    "confidence": 1.0,
                    "field_type": "mail-header",
                    "property": {
                        "content": "rel:mailcc",
                        "label_content": "",
                        "lemma_content": "rel:mailcc",
                        "positions": [-1],
                    },
                    "subject": {
                        "content": "john.enerson@enron.com",
                        "label_content": "",
                        "lemma_content": "john.enerson@enron.com",
                        "positions": [-1],
                    },
                    "value": {
                        "content": "randy.petersen@enron.com",
                        "label_content": "",
                        "lemma_content": "randy.petersen@enron.com",
                        "positions": [-1],
                    },
                    "weight": 0.0,
                },
                {
                    "automatically_fill": True,
                    "confidence": 1.0,
                    "field_type": "mail-header",
                    "property": {
                        "content": "rel:mailcc",
                        "label_content": "",
                        "lemma_content": "rel:mailcc",
                        "positions": [-1],
                    },
                    "subject": {
                        "content": "john.enerson@enron.com",
                        "label_content": "",
                        "lemma_content": "john.enerson@enron.com",
                        "positions": [-1],
                    },
                    "value": {
                        "content": "dan.lyons@enron.com",
                        "label_content": "",
                        "lemma_content": "dan.lyons@enron.com",
                        "positions": [-1],
                    },
                    "weight": 0.0,
                },
                {
                    "automatically_fill": True,
                    "confidence": 1.0,
                    "field_type": "mail-header",
                    "property": {
                        "content": "rel:mailcc",
                        "label_content": "",
                        "lemma_content": "rel:mailcc",
                        "positions": [-1],
                    },
                    "subject": {
                        "content": "John Enerso",
                        "label_content": "",
                        "lemma_content": "John Enerso",
                        "positions": [-1],
                    },
                    "value": {
                        "content": "Richard Lydecker",
                        "label_content": "",
                        "lemma_content": "Richard Lydecker",
                        "positions": [-1],
                    },
                    "weight": 0.0,
                },
                {
                    "automatically_fill": True,
                    "confidence": 1.0,
                    "field_type": "mail-header",
                    "property": {
                        "content": "rel:mailcc",
                        "label_content": "",
                        "lemma_content": "rel:mailcc",
                        "positions": [-1],
                    },
                    "subject": {
                        "content": "John Enerso",
                        "label_content": "",
                        "lemma_content": "John Enerso",
                        "positions": [-1],
                    },
                    "value": {
                        "content": "Randy Petersen",
                        "label_content": "",
                        "lemma_content": "Randy Petersen",
                        "positions": [-1],
                    },
                    "weight": 0.0,
                },
                {
                    "automatically_fill": True,
                    "confidence": 1.0,
                    "field_type": "mail-header",
                    "property": {
                        "content": "rel:mailcc",
                        "label_content": "",
                        "lemma_content": "rel:mailcc",
                        "positions": [-1],
                    },
                    "subject": {
                        "content": "John Enerso",
                        "label_content": "",
                        "lemma_content": "John Enerso",
                        "positions": [-1],
                    },
                    "value": {"content": "Dan Lyon", "label_content": "", "lemma_content": "Dan Lyon", "positions": [-1]},
                    "weight": 0.0,
                },
                {
                    "automatically_fill": True,
                    "confidence": 1.0,
                    "field_type": "mail-header",
                    "property": {
                        "content": "rel:instanceof",
                        "label_content": "",
                        "lemma_content": "rel:instanceof",
                        "positions": [-1],
                    },
                    "subject": {
                        "content": "Richard Lydecker",
                        "label_content": "",
                        "lemma_content": "Richard Lydecker",
                        "positions": [-1],
                    },
                    "value": {"content": "person", "label_content": "", "lemma_content": "person", "positions": [-1]},
                    "weight": 0.0,
                },
                {
                    "automatically_fill": True,
                    "confidence": 1.0,
                    "field_type": "mail-header",
                    "property": {
                        "content": "rel:instanceof",
                        "label_content": "",
                        "lemma_content": "rel:instanceof",
                        "positions": [-1],
                    },
                    "subject": {
                        "content": "Randy Petersen",
                        "label_content": "",
                        "lemma_content": "Randy Petersen",
                        "positions": [-1],
                    },
                    "value": {"content": "person", "label_content": "", "lemma_content": "person", "positions": [-1]},
                    "weight": 0.0,
                },
                {
                    "automatically_fill": True,
                    "confidence": 1.0,
                    "field_type": "mail-header",
                    "property": {
                        "content": "rel:instanceof",
                        "label_content": "",
                        "lemma_content": "rel:instanceof",
                        "positions": [-1],
                    },
                    "subject": {"content": "Dan Lyon", "label_content": "", "lemma_content": "Dan Lyon", "positions": [-1]},
                    "value": {"content": "person", "label_content": "", "lemma_content": "person", "positions": [-1]},
                    "weight": 0.0,
                },
                {
                    "automatically_fill": True,
                    "confidence": 1.0,
                    "field_type": "mail-header",
                    "property": {
                        "content": "rel:mailbcc",
                        "label_content": "",
                        "lemma_content": "rel:mailbcc",
                        "positions": [-1],
                    },
                    "subject": {
                        "content": "john.enerson@enron.com",
                        "label_content": "",
                        "lemma_content": "john.enerson@enron.com",
                        "positions": [-1],
                    },
                    "value": {
                        "content": "richard.lydecker@enron.com",
                        "label_content": "",
                        "lemma_content": "richard.lydecker@enron.com",
                        "positions": [-1],
                    },
                    "weight": 0.0,
                },
                {
                    "automatically_fill": True,
                    "confidence": 1.0,
                    "field_type": "mail-header",
                    "property": {
                        "content": "rel:mailbcc",
                        "label_content": "",
                        "lemma_content": "rel:mailbcc",
                        "positions": [-1],
                    },
                    "subject": {
                        "content": "john.enerson@enron.com",
                        "label_content": "",
                        "lemma_content": "john.enerson@enron.com",
                        "positions": [-1],
                    },
                    "value": {
                        "content": "randy.petersen@enron.com",
                        "label_content": "",
                        "lemma_content": "randy.petersen@enron.com",
                        "positions": [-1],
                    },
                    "weight": 0.0,
                },
                {
                    "automatically_fill": True,
                    "confidence": 1.0,
                    "field_type": "mail-header",
                    "property": {
                        "content": "rel:mailbcc",
                        "label_content": "",
                        "lemma_content": "rel:mailbcc",
                        "positions": [-1],
                    },
                    "subject": {
                        "content": "john.enerson@enron.com",
                        "label_content": "",
                        "lemma_content": "john.enerson@enron.com",
                        "positions": [-1],
                    },
                    "value": {
                        "content": "dan.lyons@enron.com",
                        "label_content": "",
                        "lemma_content": "dan.lyons@enron.com",
                        "positions": [-1],
                    },
                    "weight": 0.0,
                },
                {
                    "automatically_fill": True,
                    "confidence": 1.0,
                    "field_type": "mail-header",
                    "property": {
                        "content": "rel:instanceof",
                        "label_content": "",
                        "lemma_content": "rel:instanceof",
                        "positions": [-1],
                    },
                    "subject": {
                        "content": "Tue, 30 Jan 2001 02:35:00 -0800",
                        "label_content": "",
                        "lemma_content": "Tue, 30 Jan 2001 02:35:00 -0800",
                        "positions": [-1],
                    },
                    "value": {"content": "date", "label_content": "", "lemma_content": "date", "positions": [-1]},
                    "weight": 0.0,
                },
                {
                    "subject": {
                        "content": ["amount"],
                        "lemma_content": ["amount"],
                        "pos": ["NOUN"],
                        "positions": [26],
                        "label": "pattern_syntagm_or_prep_group",
                    },
                    "property": {
                        "content": ["is", "increased"],
                        "lemma_content": ["be", "increase"],
                        "pos": ["VERB", "VERB"],
                        "positions": [27, 28],
                        "label": "pattern_verb_phrase",
                    },
                    "value": {
                        "content": ["4.5", "million"],
                        "lemma_content": ["4.5", "million"],
                        "pos": ["NUM", "NUM"],
                        "positions": [30, 31],
                        "label": "money",
                    },
                    "automatically_fill": True,
                    "confidence": 0.0,
                    "weight": 0.0,
                    "field_type": "content",
                },
                {
                    "subject": {
                        "content": ["Completion", "Date"],
                        "lemma_content": ["completion", "Date"],
                        "pos": ["NOUN", "PROPN"],
                        "positions": [44, 45],
                        "label": "pattern_syntagm_or_prep_group",
                    },
                    "property": {
                        "content": ["is", "defined", "in"],
                        "lemma_content": ["be", "define", "in"],
                        "pos": ["VERB", "VERB", "ADP"],
                        "positions": [46, 47, 48],
                        "label": "pattern_verb_phrase",
                    },
                    "value": {
                        "content": ["Indenture"],
                        "lemma_content": ["Indenture"],
                        "pos": ["PROPN"],
                        "positions": [54],
                        "label": "organization",
                    },
                    "automatically_fill": True,
                    "confidence": 0.0,
                    "weight": 0.0,
                    "field_type": "content",
                },
                {
                    "subject": {
                        "content": ["definition"],
                        "lemma_content": ["definition"],
                        "pos": ["NOUN"],
                        "positions": [59],
                        "label": "pattern_syntagm_or_prep_group",
                    },
                    "property": {
                        "content": ["is", "exactly"],
                        "lemma_content": ["be", "exactly"],
                        "pos": ["VERB", "ADV"],
                        "positions": [60, 61],
                        "label": "pattern_verb_phrase",
                    },
                    "value": {
                        "content": ["same"],
                        "lemma_content": ["same"],
                        "pos": ["ADJ"],
                        "positions": [63],
                        "label": "pattern_syntagm_or_prep_group",
                    },
                    "automatically_fill": True,
                    "confidence": 0.0,
                    "weight": 0.0,
                    "field_type": "content",
                },
                {
                    "subject": {
                        "content": ["Approval", "of", "these", "specifications"],
                        "lemma_content": ["approval", "of", "these", "specification"],
                        "pos": ["NOUN", "ADP", "DET", "NOUN"],
                        "positions": [113, 114, 115, 116],
                        "label": "pattern_syntagm_or_prep_group",
                    },
                    "property": {
                        "content": ["must", "be", "made", "by"],
                        "lemma_content": ["must", "be", "make", "by"],
                        "pos": ["AUX", "VERB", "VERB", "ADP"],
                        "positions": [117, 118, 119, 120],
                        "label": "pattern_verb_phrase",
                    },
                    "value": {
                        "content": ["independent", "engineer"],
                        "lemma_content": ["independent", "engineer"],
                        "pos": ["ADJ", "NOUN"],
                        "positions": [122, 123],
                        "label": "pattern_syntagm_or_prep_group",
                    },
                    "automatically_fill": True,
                    "confidence": 0.0,
                    "weight": 0.0,
                    "field_type": "content",
                },
                {
                    "subject": {
                        "content": ["Approval"],
                        "lemma_content": ["approval"],
                        "pos": ["NOUN"],
                        "positions": [113],
                        "label": "dep_subject",
                    },
                    "property": {
                        "content": ["must", "be", "made"],
                        "lemma_content": ["must", "be", "make"],
                        "pos": ["AUX", "VERB", "VERB"],
                        "positions": [117, 118, 119],
                        "label": "dep_verb",
                    },
                    "value": {
                        "content": ["engineer"],
                        "lemma_content": ["engineer"],
                        "pos": ["NOUN"],
                        "positions": [123],
                        "label": "dep_object",
                    },
                    "automatically_fill": True,
                    "confidence": 0.0,
                    "weight": 0.0,
                    "field_type": "content",
                },
                {
                    "subject": {
                        "content": ["approach"],
                        "lemma_content": ["approach"],
                        "pos": ["NOUN"],
                        "positions": [135],
                        "label": "pattern_syntagm_or_prep_group",
                    },
                    "property": {
                        "content": ["regarding"],
                        "lemma_content": ["regard"],
                        "pos": ["VERB"],
                        "positions": [136],
                        "label": "pattern_verb_phrase",
                    },
                    "value": {
                        "content": ["completion"],
                        "lemma_content": ["completion"],
                        "pos": ["NOUN"],
                        "positions": [137],
                        "label": "pattern_syntagm_or_prep_group",
                    },
                    "automatically_fill": True,
                    "confidence": 0.0,
                    "weight": 0.0,
                    "field_type": "content",
                },
                {
                    "subject": {
                        "content": ["LC"],
                        "lemma_content": ["LC"],
                        "pos": ["PROPN"],
                        "positions": [166],
                        "label": "pattern_syntagm_or_prep_group",
                    },
                    "property": {
                        "content": ["expires", "on"],
                        "lemma_content": ["expire", "on"],
                        "pos": ["VERB", "ADP"],
                        "positions": [167, 168],
                        "label": "pattern_verb_phrase",
                    },
                    "value": {
                        "content": ["June", "30"],
                        "lemma_content": ["June", "30"],
                        "pos": ["PROPN", "NUM"],
                        "positions": [169, 170],
                        "label": "date",
                    },
                    "automatically_fill": True,
                    "confidence": 0.0,
                    "weight": 0.0,
                    "field_type": "content",
                },
                {
                    "subject": {
                        "content": ["LC"],
                        "lemma_content": ["LC"],
                        "pos": ["PROPN"],
                        "positions": [166],
                        "label": "pattern_syntagm_or_prep_group",
                    },
                    "property": {
                        "content": ["expires", "on"],
                        "lemma_content": ["expire", "on"],
                        "pos": ["VERB", "ADP"],
                        "positions": [167, 168],
                        "label": "pattern_verb_phrase",
                    },
                    "value": {
                        "content": ["June", "30"],
                        "lemma_content": ["June", "30"],
                        "pos": ["PROPN", "NUM"],
                        "positions": [169, 170],
                        "label": "date",
                    },
                    "automatically_fill": True,
                    "confidence": 0.0,
                    "weight": 0.0,
                    "field_type": "content",
                },
            ]
            self.assertEqual(test["title_deps"], tkeir_doc["title_deps"])
            self.assertEqual(test["content_deps"], tkeir_doc["content_deps"])
            self.assertEqual(test["kg"], tkeir_doc["kg"])

            # test 500
            json_request = {"xxx": "email", "src": "file://" + os.path.join(data_path, "mail1.txt"), "data": "bad entry"}
            r = requests.post("https://localhost:10004/api/syntactictagger/run", json=json_request, verify=ssl_verify)
            self.assertEqual(r.status_code, 500)
