{{- if and .Values.keycloak.enabled (not .Values.keycloak.useExisting) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: tkeir-keycloak-realm
  labels:
    app.kubernetes.io/name: tkeir-keycloak
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  realm-tkeir.json: |
{{ .Files.Get "realm-tkeir.json" | indent 4 }}
{{- end }}
