# Project information
site_name: T-KEIR
site_description: 'Thales knowledge extraction to information retrieval'
site_author: 'Thales'
site_url: 'https://github.com/ThalesGroup/t-keir/'
nav:
    - Home: 'index.md'
    - Overview: 'overview.md'
    - Conception: 'conception.md'
    - Installation: 'installation.md'
    - Dev Container: 'devcontainer.md'
    - Quickstart: 'ready_to_run.md'
    - Tools: 
        - Tools overview: 'tools/tools_overview.md'
        - API reference: 'tools/api_reference.md'
        - Vespa RAG: 'tools/vespa_rag.md'
        - HMI: 'hmi.md'
        - Converter: 'tools/converter.md'
        - Tokenizer: 'tools/tokenizer.md'
        - Morphosyntactic tagger: 'tools/mstagger.md'
        - Named Entities Tagger: 'tools/nertagger.md'
        - Syntactic Tagger : 'tools/syntactictagger.md'
        - Keywords Extraction: 'tools/keywords.md'
    - Security: 'security.md'
    - Operation and Management: 'oam.md'
    - About: 'about.md'
plugins:
    - render_swagger
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Repository
repo_name: 'ThalesGroup/t-keir'
repo_url: 'https://github.com/ThalesGroup/t-keir/'

# Copyright
copyright: |
  Copyright &copy; 2022 THALES<br>

# Configuration
theme:
  logo: 'logos/png/T-KEIR_logo_FIN-04.png'
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
     - navigation.tabs

# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/ThalesGroup'
