# -*- coding: utf-8 -*-
"""Test Embeddings
Author: Eric Blaudez (Eric Blaudez)

Copyright (c) 2020 by THALES
"""

import unittest
from thot.core.ThotLogger import ThotLogger, LogUserContext
from thot.tasks.embeddings.EmbeddingsConfiguration import EmbeddingsConfiguration
from thot.tasks.embeddings.Embeddings import Embeddings
import json
from uuid import uuid4

embeddings = None
config = None


class TestEmbeddings(unittest.TestCase):

    embedding_config = {
        "logger": {"logging-level": "debug"},
        "embeddings": {
            "models": [{"language": "multi", "use-cuda": False}],
            "network": {
                "host": "0.0.0.0",
                "port": 8080,
                "associate-environment": {"host": "HOST_ENVNAME", "port": "PORT_ENVNAME"},
            },
            "runtime": {
                "request-max-size": 100000000,
                "request-buffer-queue-size": 100,
                "keep-alive": True,
                "keep-alive-timeout": 5,
                "graceful-shutown-timeout": 15.0,
                "request-timeout": 60,
                "response-timeout": 60,
                "workers": 1,
            },
            "serialize": {
                "input": {"path": "/tmp", "keep-service-info": True},
                "output": {"path": "/tmp", "keep-service-info": True},
            },
        },
    }

    @classmethod
    def setUpClass(self):
        global embeddings
        global config
        config = EmbeddingsConfiguration()
        config.loads(TestEmbeddings.embedding_config)
        ThotLogger.loads(config.logger_config.configuration)
        embeddings = Embeddings(config)

    def test_generate_sentences_from_token(self):
        global embeddings
        test_sentences = [
            [
                {"token": "aa", "start_sentence": False},
                {"token": "bb", "start_sentence": False},
                {"token": "cc", "start_sentence": False},
            ],
            [
                [{"token": "dd", "start_sentence": False}, {"token": "gg", "start_sentence": False}],
                [
                    [{"token": "ee", "start_sentence": False}],
                    [
                        {"token": "ff", "start_sentence": False},
                        {"token": "hh", "start_sentence": False},
                        {"token": "ii", "start_sentence": False},
                    ],
                ],
            ],
            [
                {"token": "1", "start_sentence": False},
                {"token": "2", "start_sentence": False},
                {"token": "3", "start_sentence": False},
                {"token": "4", "start_sentence": False},
                {"token": "5", "start_sentence": False},
                {"token": "6", "start_sentence": False},
                {"token": "7", "start_sentence": False},
                {"token": "8", "start_sentence": False},
                {"token": "9", "start_sentence": False},
                {"token": "0", "start_sentence": False},
                {"token": "1", "start_sentence": False},
                {"token": "2", "start_sentence": False},
                {"token": "3", "start_sentence": False},
                {"token": "4", "start_sentence": False},
                {"token": "5", "start_sentence": False},
                {"token": "6", "start_sentence": False},
                {"token": "7", "start_sentence": False},
                {"token": "8", "start_sentence": False},
                {"token": "9", "start_sentence": False},
                {"token": "0", "start_sentence": False},
                {"token": "1", "start_sentence": False},
                {"token": "2", "start_sentence": False},
                {"token": "3", "start_sentence": False},
                {"token": "4", "start_sentence": False},
                {"token": "5", "start_sentence": False},
                {"token": "6", "start_sentence": False},
                {"token": "7", "start_sentence": False},
                {"token": "8", "start_sentence": False},
                {"token": "9", "start_sentence": False},
                {"token": "0", "start_sentence": False},
                {"token": "1", "start_sentence": False},
                {"token": "2", "start_sentence": False},
                {"token": "3", "start_sentence": False},
                {"token": "4", "start_sentence": False},
                {"token": "5", "start_sentence": False},
                {"token": "6", "start_sentence": False},
                {"token": "7", "start_sentence": False},
                {"token": "8", "start_sentence": False},
                {"token": "9", "start_sentence": False},
                {"token": "0", "start_sentence": False},
                {"token": "1", "start_sentence": False},
                {"token": "2", "start_sentence": False},
                {"token": "3", "start_sentence": False},
                {"token": "4", "start_sentence": False},
                {"token": "5", "start_sentence": False},
                {"token": "6", "start_sentence": False},
                {"token": "7", "start_sentence": False},
                {"token": "8", "start_sentence": False},
                {"token": "9", "start_sentence": False},
                {"token": "0", "start_sentence": False},
                {"token": "1", "start_sentence": False},
                {"token": "2", "start_sentence": False},
                {"token": "3", "start_sentence": False},
                {"token": "4", "start_sentence": False},
                {"token": "5", "start_sentence": False},
                {"token": "6", "start_sentence": False},
                {"token": "7", "start_sentence": False},
                {"token": "8", "start_sentence": False},
                {"token": "9", "start_sentence": False},
                {"token": "0", "start_sentence": False},
                {"token": "1", "start_sentence": False},
                {"token": "2", "start_sentence": False},
                {"token": "3", "start_sentence": False},
                {"token": "4", "start_sentence": False},
                {"token": "5", "start_sentence": False},
                {"token": "6", "start_sentence": False},
                {"token": "7", "start_sentence": False},
                {"token": "8", "start_sentence": False},
                {"token": "9", "start_sentence": False},
                {"token": "0", "start_sentence": False},
                {"token": "1", "start_sentence": False},
                {"token": "2", "start_sentence": False},
                {"token": "3", "start_sentence": False},
                {"token": "4", "start_sentence": False},
                {"token": "5", "start_sentence": False},
                {"token": "6", "start_sentence": False},
                {"token": "7", "start_sentence": False},
                {"token": "8", "start_sentence": False},
                {"token": "9", "start_sentence": False},
                {"token": "0", "start_sentence": False},
            ],
            [
                {"token": "1", "start_sentence": False},
                {"token": "2", "start_sentence": False},
                {"token": "3", "start_sentence": False},
                {"token": "4", "start_sentence": False},
                {"token": "5", "start_sentence": False},
                {"token": "6", "start_sentence": False},
                {"token": "7", "start_sentence": False},
                {"token": "8", "start_sentence": False},
                {"token": "9", "start_sentence": False},
                {"token": "0", "start_sentence": False},
                {"token": "1", "start_sentence": False},
                {"token": "2", "start_sentence": False},
                {"token": "3", "start_sentence": False},
                {"token": "4", "start_sentence": False},
                {"token": "5", "start_sentence": False},
                {"token": "6", "start_sentence": False},
                {"token": "7", "start_sentence": False},
                {"token": "8", "start_sentence": False},
                {"token": "9", "start_sentence": False},
                {"token": "0", "start_sentence": False},
                {"token": "1", "start_sentence": False},
                {"token": "2", "start_sentence": False},
                {"token": "3", "start_sentence": False},
                {"token": "4", "start_sentence": False},
                {"token": "5", "start_sentence": False},
                {"token": "6", "start_sentence": False},
                {"token": "7", "start_sentence": False},
                {"token": "8", "start_sentence": False},
                {"token": "9", "start_sentence": False},
                {"token": "0", "start_sentence": False},
                {"token": "1", "start_sentence": False},
                {"token": "2", "start_sentence": False},
                {"token": "3", "start_sentence": False},
                {"token": "4", "start_sentence": False},
                {"token": "5", "start_sentence": False},
                {"token": "6", "start_sentence": False},
                {"token": "7", "start_sentence": False},
                {"token": "8", "start_sentence": False},
                {"token": "9", "start_sentence": False},
                {"token": "0", "start_sentence": False},
                {"token": "1", "start_sentence": False},
                {"token": "2", "start_sentence": False},
                {"token": "3", "start_sentence": False},
                {"token": "4", "start_sentence": False},
                {"token": "5", "start_sentence": False},
                {"token": "6", "start_sentence": False},
                {"token": "7", "start_sentence": False},
                {"token": "8", "start_sentence": False},
                {"token": "9", "start_sentence": False},
                {"token": "0", "start_sentence": False},
                {"token": "1", "start_sentence": False},
                {"token": "2", "start_sentence": False},
                {"token": "3", "start_sentence": False},
                {"token": "4", "start_sentence": False},
                {"token": "5", "start_sentence": False},
                {"token": "6", "start_sentence": False},
                {"token": "7", "start_sentence": False},
                {"token": "8", "start_sentence": False},
                {"token": "9", "start_sentence": False},
                {"token": "0", "start_sentence": False},
                {"token": "1", "start_sentence": False},
                {"token": "2", "start_sentence": False},
                {"token": "3", "start_sentence": False},
                {"token": "4", "start_sentence": False},
                {"token": "5", "start_sentence": False},
                {"token": "6", "start_sentence": False},
                {"token": "7", "start_sentence": False},
                {"token": "8", "start_sentence": False},
                {"token": "9", "start_sentence": False},
                {"token": "0", "start_sentence": False},
                {"token": "1", "start_sentence": False},
                {"token": "2", "start_sentence": False},
                {"token": "3", "start_sentence": False},
                {"token": "4", "start_sentence": False},
                {"token": "5", "start_sentence": False},
                {"token": "6", "start_sentence": False},
                {"token": "7", "start_sentence": False},
                {"token": "8", "start_sentence": False},
                {"token": "9", "start_sentence": False},
                {"token": "0", "start_sentence": False},
            ],
        ]

        test_result = [
            "aa bb cc",
            "dd gg",
            "ee",
            "ff hh ii",
            "1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4",
            "5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0",
            "1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4",
            "5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0",
        ]
        sentences = []

        embeddings._generate_sentences_from_token(test_sentences, sentences, max_length=64)
        self.assertEqual(sentences, test_result)

    def test_embeddings(self):
        global embeddings
        text = [
            [
                "A new study is the first to identify how human brains grow much larger, with three times as many neurons, compared with chimpanzee and gorilla brains. The study, led by researchers at the Medical Research Council (MRC) Laboratory of Molecular Biology in Cambridge, UK, identified a key molecular switch that can make ape brain organoids grow more like human organoids, and vice versa."
            ],
            [
                "The study, published in the journal Cell, compared 'brain organoids' -- 3D tissues grown from stem cells which model early brain development -- that were grown from human, gorilla and chimpanzee stem cells.Similar to actual brains, the human brain organoids grew a lot larger than the organoids from other apes.Dr Madeline Lancaster, from the MRC Laboratory of Molecular Biology, who led the study, said: This provides some of the first insight into what is different about the developing human brain that sets us apart from our closest living relatives, the other great apes. The most striking difference between us and other apes is just how incredibly big our brains are.During the early stages of brain development, neurons are made by stem cells called neural progenitors. These progenitor cells initially have a cylindrical shape that makes it easy for them to split into identical daughter cells with the same shape."
            ],
        ]
        tkeir_doc = {
            "data_source": "tokenizer-service",
            "source_doc_id": "file://test.txt",
            "title": "Access to UBSWenergy Production Environment",
            "content": [
                [
                    "A new study is the first to identify how human brains grow much larger, with three times as many neurons, compared with chimpanzee and gorilla brains. The study, led by researchers at the Medical Research Council (MRC) Laboratory of Molecular Biology in Cambridge, UK, identified a key molecular switch that can make ape brain organoids grow more like human organoids, and vice versa."
                ],
                [
                    "The study, published in the journal Cell, compared 'brain organoids' -- 3D tissues grown from stem cells which model early brain development -- that were grown from human, gorilla and chimpanzee stem cells.Similar to actual brains, the human brain organoids grew a lot larger than the organoids from other apes.Dr Madeline Lancaster, from the MRC Laboratory of Molecular Biology, who led the study, said: This provides some of the first insight into what is different about the developing human brain that sets us apart from our closest living relatives, the other great apes. The most striking difference between us and other apes is just how incredibly big our brains are.During the early stages of brain development, neurons are made by stem cells called neural progenitors. These progenitor cells initially have a cylindrical shape that makes it easy for them to split into identical daughter cells with the same shape."
                ],
            ],
            "content_tokens": [
                [
                    [
                        [
                            {"token": "A", "start_sentence": True},
                            {"token": "new", "start_sentence": False},
                            {"token": "study", "start_sentence": False},
                            {"token": "is", "start_sentence": False},
                            {"token": "the", "start_sentence": False},
                            {"token": "first", "start_sentence": False},
                            {"token": "to", "start_sentence": False},
                            {"token": "identify", "start_sentence": False},
                            {"token": "how", "start_sentence": False},
                            {"token": "human", "start_sentence": False},
                            {"token": "brains", "start_sentence": False},
                            {"token": "grow", "start_sentence": False},
                            {"token": "much", "start_sentence": False},
                            {"token": "larger", "start_sentence": False},
                            {"token": ",", "start_sentence": False},
                            {"token": "with", "start_sentence": False},
                            {"token": "three", "start_sentence": False},
                            {"token": "times", "start_sentence": False},
                            {"token": "as", "start_sentence": False},
                            {"token": "many", "start_sentence": False},
                            {"token": "neurons", "start_sentence": False},
                            {"token": ",", "start_sentence": False},
                            {"token": "compared", "start_sentence": False},
                            {"token": "with", "start_sentence": False},
                            {"token": "chimpanzee", "start_sentence": False},
                            {"token": "and", "start_sentence": False},
                            {"token": "gorilla", "start_sentence": False},
                            {"token": "brains", "start_sentence": False},
                            {"token": ".", "start_sentence": False},
                        ],
                        [
                            {"token": "The", "start_sentence": True},
                            {"token": "study", "start_sentence": False},
                            {"token": ",", "start_sentence": False},
                            {"token": "led", "start_sentence": False},
                            {"token": "by", "start_sentence": False},
                            {"token": "researchers", "start_sentence": False},
                            {"token": "at", "start_sentence": False},
                            {"token": "the", "start_sentence": False},
                            {"token": "Medical", "start_sentence": False},
                            {"token": "Research", "start_sentence": False},
                            {"token": "Council", "start_sentence": False},
                            {"token": "(", "start_sentence": False},
                            {"token": "MRC", "start_sentence": False},
                            {"token": ")", "start_sentence": False},
                            {"token": "Laboratory", "start_sentence": False},
                            {"token": "of", "start_sentence": False},
                            {"token": "Molecular", "start_sentence": False},
                            {"token": "Biology", "start_sentence": False},
                            {"token": "in", "start_sentence": False},
                            {"token": "Cambridge", "start_sentence": False},
                            {"token": ",", "start_sentence": False},
                            {"token": "UK", "start_sentence": False},
                            {"token": ",", "start_sentence": False},
                            {"token": "identified", "start_sentence": False},
                            {"token": "a", "start_sentence": False},
                            {"token": "key", "start_sentence": False},
                            {"token": "molecular", "start_sentence": False},
                            {"token": "switch", "start_sentence": False},
                            {"token": "that", "start_sentence": False},
                            {"token": "can", "start_sentence": False},
                            {"token": "make", "start_sentence": False},
                            {"token": "ape", "start_sentence": False},
                            {"token": "brain", "start_sentence": False},
                            {"token": "organoids", "start_sentence": False},
                            {"token": "grow", "start_sentence": False},
                            {"token": "more", "start_sentence": False},
                            {"token": "like", "start_sentence": False},
                            {"token": "human", "start_sentence": False},
                            {"token": "organoids", "start_sentence": False},
                            {"token": ",", "start_sentence": False},
                            {"token": "and", "start_sentence": False},
                            {"token": "vice", "start_sentence": False},
                            {"token": "versa", "start_sentence": False},
                            {"token": ".", "start_sentence": False},
                        ],
                    ]
                ],
                [
                    [
                        [
                            {"token": "The", "start_sentence": True},
                            {"token": "study", "start_sentence": False},
                            {"token": ",", "start_sentence": False},
                            {"token": "published", "start_sentence": False},
                            {"token": "in", "start_sentence": False},
                            {"token": "the", "start_sentence": False},
                            {"token": "journal", "start_sentence": False},
                            {"token": "Cell", "start_sentence": False},
                            {"token": ",", "start_sentence": False},
                            {"token": "compared", "start_sentence": False},
                            {"token": "'", "start_sentence": False},
                            {"token": "brain", "start_sentence": False},
                            {"token": "organoids", "start_sentence": False},
                            {"token": "' --", "start_sentence": False},
                            {"token": "3D", "start_sentence": False},
                            {"token": "tissues", "start_sentence": False},
                            {"token": "grown", "start_sentence": False},
                            {"token": "from", "start_sentence": False},
                            {"token": "stem", "start_sentence": False},
                            {"token": "cells", "start_sentence": False},
                            {"token": "which", "start_sentence": False},
                            {"token": "model", "start_sentence": False},
                            {"token": "early", "start_sentence": False},
                            {"token": "brain", "start_sentence": False},
                            {"token": "development", "start_sentence": False},
                            {"token": "--", "start_sentence": False},
                            {"token": "that", "start_sentence": False},
                            {"token": "were", "start_sentence": False},
                            {"token": "grown", "start_sentence": False},
                            {"token": "from", "start_sentence": False},
                            {"token": "human", "start_sentence": False},
                            {"token": ",", "start_sentence": False},
                            {"token": "gorilla", "start_sentence": False},
                            {"token": "and", "start_sentence": False},
                            {"token": "chimpanzee", "start_sentence": False},
                            {"token": "stem", "start_sentence": False},
                            {"token": "cells", "start_sentence": False},
                            {"token": ".", "start_sentence": False},
                            {"token": "Similar", "start_sentence": False},
                            {"token": "to", "start_sentence": False},
                            {"token": "actual", "start_sentence": False},
                            {"token": "brains", "start_sentence": False},
                            {"token": ",", "start_sentence": False},
                            {"token": "the", "start_sentence": False},
                            {"token": "human", "start_sentence": False},
                            {"token": "brain", "start_sentence": False},
                            {"token": "organoids", "start_sentence": False},
                            {"token": "grew", "start_sentence": False},
                            {"token": "a", "start_sentence": False},
                            {"token": "lot", "start_sentence": False},
                            {"token": "larger", "start_sentence": False},
                            {"token": "than", "start_sentence": False},
                            {"token": "the", "start_sentence": False},
                            {"token": "organoids", "start_sentence": False},
                            {"token": "from", "start_sentence": False},
                            {"token": "other", "start_sentence": False},
                            {"token": "apes", "start_sentence": False},
                            {"token": ".", "start_sentence": False},
                            {"token": "Dr", "start_sentence": False},
                            {"token": "Madeline", "start_sentence": False},
                            {"token": "Lancaster", "start_sentence": False},
                            {"token": ",", "start_sentence": False},
                            {"token": "from", "start_sentence": False},
                            {"token": "the", "start_sentence": False},
                            {"token": "MRC", "start_sentence": False},
                            {"token": "Laboratory", "start_sentence": False},
                            {"token": "of", "start_sentence": False},
                            {"token": "Molecular", "start_sentence": False},
                            {"token": "Biology", "start_sentence": False},
                            {"token": ",", "start_sentence": False},
                            {"token": "who", "start_sentence": False},
                            {"token": "led", "start_sentence": False},
                            {"token": "the", "start_sentence": False},
                            {"token": "study", "start_sentence": False},
                            {"token": ",", "start_sentence": False},
                            {"token": "said", "start_sentence": False},
                            {"token": ":", "start_sentence": False},
                            {"token": "This", "start_sentence": False},
                            {"token": "provides", "start_sentence": False},
                            {"token": "some", "start_sentence": False},
                            {"token": "of", "start_sentence": False},
                            {"token": "the", "start_sentence": False},
                            {"token": "first", "start_sentence": False},
                            {"token": "insight", "start_sentence": False},
                            {"token": "into", "start_sentence": False},
                            {"token": "what", "start_sentence": False},
                            {"token": "is", "start_sentence": False},
                            {"token": "different", "start_sentence": False},
                            {"token": "about", "start_sentence": False},
                            {"token": "the", "start_sentence": False},
                            {"token": "developing", "start_sentence": False},
                            {"token": "human", "start_sentence": False},
                            {"token": "brain", "start_sentence": False},
                            {"token": "that", "start_sentence": False},
                            {"token": "sets", "start_sentence": False},
                            {"token": "us", "start_sentence": False},
                            {"token": "apart", "start_sentence": False},
                            {"token": "from", "start_sentence": False},
                            {"token": "our", "start_sentence": False},
                            {"token": "closest", "start_sentence": False},
                            {"token": "living", "start_sentence": False},
                            {"token": "relatives", "start_sentence": False},
                            {"token": ",", "start_sentence": False},
                            {"token": "the", "start_sentence": False},
                            {"token": "other", "start_sentence": False},
                            {"token": "great", "start_sentence": False},
                            {"token": "apes", "start_sentence": False},
                            {"token": ".", "start_sentence": False},
                        ],
                        [
                            {"token": "The", "start_sentence": True},
                            {"token": "most", "start_sentence": False},
                            {"token": "striking", "start_sentence": False},
                            {"token": "difference", "start_sentence": False},
                            {"token": "between", "start_sentence": False},
                            {"token": "us", "start_sentence": False},
                            {"token": "and", "start_sentence": False},
                            {"token": "other", "start_sentence": False},
                            {"token": "apes", "start_sentence": False},
                            {"token": "is", "start_sentence": False},
                            {"token": "just", "start_sentence": False},
                            {"token": "how", "start_sentence": False},
                            {"token": "incredibly", "start_sentence": False},
                            {"token": "big", "start_sentence": False},
                            {"token": "our", "start_sentence": False},
                            {"token": "brains", "start_sentence": False},
                            {"token": "are", "start_sentence": False},
                            {"token": ".", "start_sentence": False},
                            {"token": "During", "start_sentence": False},
                            {"token": "the", "start_sentence": False},
                            {"token": "early", "start_sentence": False},
                            {"token": "stages", "start_sentence": False},
                            {"token": "of", "start_sentence": False},
                            {"token": "brain", "start_sentence": False},
                            {"token": "development", "start_sentence": False},
                            {"token": ",", "start_sentence": False},
                            {"token": "neurons", "start_sentence": False},
                            {"token": "are", "start_sentence": False},
                            {"token": "made", "start_sentence": False},
                            {"token": "by", "start_sentence": False},
                            {"token": "stem", "start_sentence": False},
                            {"token": "cells", "start_sentence": False},
                            {"token": "called", "start_sentence": False},
                            {"token": "neural", "start_sentence": False},
                            {"token": "progenitors", "start_sentence": False},
                            {"token": ".", "start_sentence": False},
                        ],
                        [
                            {"token": "These", "start_sentence": True},
                            {"token": "progenitor", "start_sentence": False},
                            {"token": "cells", "start_sentence": False},
                            {"token": "initially", "start_sentence": False},
                            {"token": "have", "start_sentence": False},
                            {"token": "a", "start_sentence": False},
                            {"token": "cylindrical", "start_sentence": False},
                            {"token": "shape", "start_sentence": False},
                            {"token": "that", "start_sentence": False},
                            {"token": "makes", "start_sentence": False},
                            {"token": "it", "start_sentence": False},
                            {"token": "easy", "start_sentence": False},
                            {"token": "for", "start_sentence": False},
                            {"token": "them", "start_sentence": False},
                            {"token": "to", "start_sentence": False},
                            {"token": "split", "start_sentence": False},
                            {"token": "into", "start_sentence": False},
                            {"token": "identical", "start_sentence": False},
                            {"token": "daughter", "start_sentence": False},
                            {"token": "cells", "start_sentence": False},
                            {"token": "with", "start_sentence": False},
                            {"token": "the", "start_sentence": False},
                            {"token": "same", "start_sentence": False},
                            {"token": "shape", "start_sentence": False},
                            {"token": ".", "start_sentence": False},
                        ],
                    ]
                ],
            ],
            "title_tokens": [
                [
                    {"token": "Access", "start_sentence": True},
                    {"token": "to", "start_sentence": False},
                    {"token": "UBSWenergy", "start_sentence": False},
                    {"token": "Production", "start_sentence": False},
                    {"token": "Environment", "start_sentence": False},
                ]
            ],
        }
        cid = "autogenerated-" + str(uuid4())
        log_context = LogUserContext(cid)
        tkeir_doc = embeddings.compute(tkeir_doc, call_context=log_context)
        self.assertTrue(True)
