# -*- coding: utf-8 -*-
"""Convert source document to tkeir indexer document
Author: Eric Blaudez (Eric Blaudez)

Copyright (c) 2020 by THALES
"""

from thot.core.ThotLogger import ThotLogger, LogUserContext
from thot.tasks.document_classification.ZeroShotClassificationConfiguration import ZeroShotClassificationConfiguration
from thot.tasks.document_classification.ZeroShotClassification import ZeroShotClassification
import os
import json
import unittest

dir_path = os.path.dirname(os.path.realpath(__file__))
test_file_path = os.path.abspath(os.path.join(dir_path, "../data/test-outputs-syntax"))


class TestZeroShotClassification(unittest.TestCase):

    zsc_config = {
        "logger": {"logging-level": "debug"},
        "zeroshot-classification": {
            "classes": [
                {"label": "machine learning", "content": ["machine learning", "learning algorithm", "modeling"]},
                {"label": "neural network", "content": ["neural network", "hidden layers", "loss function"]},
                {
                    "label": "image processing",
                    "content": ["convolutional neural network", "fourier", "cosine transform", "image", "picture", "draw"],
                },
                {"label": "natural language processing", "content": ["natural language processing", "named entities"]},
            ],
            "network": {
                "host": "0.0.0.0",
                "port": 8080,
                "associate-environment": {"host": "HOST_ENVNAME", "port": "PORT_ENVNAME"},
            },
            "runtime": {
                "request-max-size": 100000000,
                "request-buffer-queue-size": 100,
                "keep-alive": True,
                "keep-alive-timeout": 5,
                "graceful-shutown-timeout": 15.0,
                "request-timeout": 60,
                "response-timeout": 60,
                "workers": 1,
            },
            "serialize": {
                "input": {"path": "/tmp", "keep-service-info": True},
                "output": {"path": "/tmp", "keep-service-info": True},
            },
        },
    }

    def test_kwe(self):
        config = ZeroShotClassificationConfiguration()
        config.loads(TestZeroShotClassification.zsc_config)
        ThotLogger.loads(config.logger_config.configuration)
        cid = "autogenerated-" + str("xxx")
        log_context = LogUserContext(cid)

        with open(os.path.join(test_file_path, "mail3.txt.converted.tokenized.ms.ner.syntax.json")) as f:
            tkeir_doc = json.load(f)
            f.close()
            zsc = ZeroShotClassification(config=config)
            tkeir_doc = zsc.classify(tkeir_doc, call_context=log_context)
            self.assertTrue("zero-shot-classification" in tkeir_doc)
            self.assertTrue("document" in tkeir_doc["zero-shot-classification"])
            self.assertTrue("title_sentences" in tkeir_doc["zero-shot-classification"])
            self.assertTrue("content_sentences" in tkeir_doc["zero-shot-classification"])
