# -*- coding: utf-8 -*-
"""Test converter
Author: Eric Blaudez (Eric Blaudez)

Copyright (c) 2020 by THALES
"""

import os
import sys
import signal
import unittest
from unittest import mock
import time
import requests
import subprocess
from thot.core.Utils import check_pid
from thot.core.ThotLogger import ThotLogger, LogUserContext
from thot.tasks.searching.Aggregator import Aggregator
from thot.tasks.searching.SearchingConfiguration import SearchingConfiguration

# This method will be used by the mock to replace requests.get
def mocked_requests_get(*args, **kwargs):
    class MockResponse:
        def __init__(self, json_data, status_code):
            self.json_data = json_data
            self.status_code = status_code

        def json(self):
            return self.json_data

    return MockResponse(
        {
            "query": "cnn",
            "number_of_results": 0,
            "results": [
                {
                    "url": "https://en.wikipedia.org/wiki/CNN",
                    "title": "CNN",
                    "engine": "wikipedia",
                    "parsed_url": ["https", "en.wikipedia.org", "/wiki/CNN", "", "", ""],
                    "engines": ["wikipedia"],
                    "positions": [1],
                    "score": 1.0,
                    "category": "general",
                    "pretty_url": "https://en.wikipedia.org/wiki/CNN",
                }
            ],
            "answers": [],
            "corrections": [],
            "infoboxes": [
                {
                    "infobox": "CNN",
                    "id": "https://en.wikipedia.org/wiki/CNN",
                    "content": "The Cable News Network (CNN) is a multinational news-based pay television channel headquartered in Atlanta, United States. It is part of AT&T's WarnerMedia. It was founded in 1980 by American media proprietor Ted Turner and Reese Schonfeld as a 24-hour cable news channel. Upon its launch in 1980, CNN was the first television channel to provide 24-hour news coverage, and was the first all-news television channel in the United States.",
                    "img_src": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/CNN.svg/320px-CNN.svg.png",
                    "urls": [{"title": "Wikipedia", "url": "https://en.wikipedia.org/wiki/CNN"}],
                    "engine": "wikipedia",
                    "engines": ["wikipedia"],
                }
            ],
            "suggestions": [],
            "unresponsive_engines": [],
        },
        200,
    )


class TestAggregator(unittest.TestCase):
    @classmethod
    def setUpClass(self):
        load_finish = False
        count = 0
        dir_path = os.path.dirname(os.path.realpath(__file__))
        res_path = os.path.abspath(os.path.join(dir_path, "../../app/projects/template/configs/search.json"))

        self.searching_config = SearchingConfiguration()
        with open(res_path, encoding="utf-8") as search_f:
            self.searching_config.load(search_f)
            ThotLogger.loads(self.searching_config.logger_config.configuration)
            search_f.close()

    @classmethod
    def tearDownClass(self):
        pass

    @mock.patch("requests.get", side_effect=mocked_requests_get)
    def test_aggregator_search(self, mock_get):
        cid = "autogenerated-" + str("xxx")
        log_context = LogUserContext(cid)
        agg = Aggregator(self.searching_config, call_context=log_context)
        results = []
        count_results = []
        for k in range(3):
            results.append(agg.third_party_search("cnn"))
            ThotLogger.info("Add" + results[-1], context=log_context)
        for k in range(3):
            agg.wait_results(results[k])
            count_results.append(len(agg.thread_results[results[k]]["results"]))
            if k > 0:
                self.assertEqual(count_results[k - 1], count_results[-1])
