"""Convert source document to tkeir indexer document
Author: Eric Blaudez (Eric Blaudez)

Copyright (c) 2020 by THALES
"""

import unittest

from thot.core.ThotLogger import LogUserContext, ThotLogger
from thot.tasks.morphosyntax.MorphoSyntacticTagger import MorphoSyntacticTagger
from thot.tasks.morphosyntax.MorphoSyntacticTaggerConfiguration import (
    MorphoSyntacticTaggerConfiguration,
)


class TestMorphoSyntacticTagger(unittest.TestCase):
    tagger_config = {
        "logger": {"logging-level": "debug"},
        "morphosyntax": {
            "taggers": [
                {
                    "language": "en",
                    "resources-base-path": (
                        "/home/tkeir_svc/tkeir/thot/tests/data"
                    ),
                    "pre-sentencizer": True,
                    "pre-tagging-with-concept": True,
                    "add-concept-in-knowledge-graph": True,
                }
            ],
        },
    }

    def test_tagger(self):
        config = MorphoSyntacticTaggerConfiguration()
        config.loads(TestMorphoSyntacticTagger.tagger_config)
        ThotLogger.loads(config.logger_config.configuration)
        cid = "autogenerated-" + "xxx"
        log_context = LogUserContext(cid)
        text = ["He lives at paris, and works at Valero Energy."]
        tkeir_doc = {
            "data_source": "tokenizer-service",
            "source_doc_id": "file://test.txt",
            "title": "Access to UBSWenergy Production Environment",
            "content": text,
            "title_tokens": [
                {"token": "Access", "start_sentence": True},
                {"token": "to", "start_sentence": False},
                {"token": "UBSWenergy", "start_sentence": False},
                {"token": "Production", "start_sentence": False},
                {"token": "Environment", "start_sentence": False},
            ],
            "content_tokens": [
                {"token": "He", "start_sentence": True},
                {"token": "lives", "start_sentence": False},
                {"token": "at", "start_sentence": False},
                {"token": "paris", "start_sentence": False},
                {"token": ",", "start_sentence": False},
                {"token": "and", "start_sentence": False},
                {"token": "works", "start_sentence": False},
                {"token": "at", "start_sentence": False},
                {"token": "Valero Energy", "start_sentence": False},
                {"token": ".", "start_sentence": False},
            ],
        }
        tagger = MorphoSyntacticTagger(config=config, call_context=log_context)
        tkeir_doc = tagger.tag(tkeir_doc)

        self.assertEqual(
            tkeir_doc["title_morphosyntax"],
            [
                {
                    "pos": "NOUN",
                    "lemma": "access",
                    "text": "Access",
                    "is_oov": False,
                    "is_sent_start": True,
                },
                {
                    "pos": "ADP",
                    "lemma": "to",
                    "text": "to",
                    "is_oov": False,
                    "is_sent_start": False,
                },
                {
                    "pos": "PROPN",
                    "lemma": "UBSWenergy",
                    "text": "UBSWenergy",
                    "is_oov": True,
                    "is_sent_start": False,
                },
                {
                    "pos": "PROPN",
                    "lemma": "Production",
                    "text": "Production",
                    "is_oov": False,
                    "is_sent_start": False,
                },
                {
                    "pos": "PROPN",
                    "lemma": "Environment",
                    "text": "Environment",
                    "is_oov": False,
                    "is_sent_start": False,
                },
            ],
        )

        self.assertEqual(
            tkeir_doc["content_morphosyntax"],
            [
                {
                    "pos": "PRON",
                    "lemma": "he",
                    "text": "He",
                    "is_oov": False,
                    "is_sent_start": True,
                },
                {
                    "pos": "VERB",
                    "lemma": "live",
                    "text": "lives",
                    "is_oov": False,
                    "is_sent_start": False,
                },
                {
                    "pos": "ADP",
                    "lemma": "at",
                    "text": "at",
                    "is_oov": False,
                    "is_sent_start": False,
                },
                {
                    "pos": "PROPN",
                    "lemma": "paris",
                    "text": "paris",
                    "is_oov": False,
                    "is_sent_start": False,
                },
                {
                    "pos": "PUNCT",
                    "lemma": ",",
                    "text": ",",
                    "is_oov": False,
                    "is_sent_start": False,
                },
                {
                    "pos": "CCONJ",
                    "lemma": "and",
                    "text": "and",
                    "is_oov": False,
                    "is_sent_start": False,
                },
                {
                    "pos": "VERB",
                    "lemma": "work",
                    "text": "works",
                    "is_oov": False,
                    "is_sent_start": False,
                },
                {
                    "pos": "ADP",
                    "lemma": "at",
                    "text": "at",
                    "is_oov": False,
                    "is_sent_start": False,
                },
                {
                    "pos": "PROPN",
                    "lemma": "Valero Energy",
                    "text": "Valero Energy",
                    "is_oov": True,
                    "is_sent_start": False,
                },
                {
                    "pos": "PUNCT",
                    "lemma": ".",
                    "text": ".",
                    "is_oov": False,
                    "is_sent_start": False,
                },
            ],
        )
