"""Title: Mark It Down Converter

Test MarkItDown converter.

Author: Eric Blaudez

Copyright (c) 2026 Thales
Licensed under the MIT License.
"""

import os
from unittest.mock import patch
from uuid import uuid4

import pytest

from thot.core.ThotLogger import LogUserContext
from thot.tasks.converters.MarkItDownConverter import MarkItDownConverter


class TestMarkItDownConverter:
    def test_email_conversion(self):
        dir_path = os.path.dirname(os.path.realpath(__file__))
        data_path = os.path.abspath(
            os.path.join(dir_path, "../fixtures/test-raw/mail")
        )
        log_context = LogUserContext("autogenerated-" + str(uuid4()))
        with open(os.path.join(data_path, "mail1.txt"), "rb") as handle:
            data = handle.read()
        document = MarkItDownConverter.convert(
            data, "file://mail1.txt", "email", call_context=log_context
        )
        assert (
            "Access to UBSWenergy Production Environment"
            in document["content"][0]
        )
        assert not document["error"]

    def test_extension_for(self):
        assert (
            MarkItDownConverter.extension_for("pdf", "file://doc.pdf")
            == ".pdf"
        )
        assert (
            MarkItDownConverter.extension_for("email", "file://mail.txt")
            == ".eml"
        )
        assert (
            MarkItDownConverter.extension_for("html", "file://doc") == ".html"
        )
        assert (
            MarkItDownConverter.extension_for("unknown", "file://notes.TXT")
            == ".txt"
        )

    def test_convert_invalid_document(self):
        with patch.object(MarkItDownConverter, "get_engine") as mock_engine:
            mock_engine.return_value.convert_stream.side_effect = RuntimeError(
                "boom"
            )
            with pytest.raises(ValueError):
                MarkItDownConverter.convert(b"bad", "file://bad.pdf", "pdf")
