{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tkeir-indexer.serviceAccountName" . }}
  labels:
    {{- include "tkeir-indexer.labels" . | nindent 4 }}
{{- end }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "tkeir-indexer.fullname" . }}
  labels:
    {{- include "tkeir-indexer.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | default "0 0 1 1 *" | quote }}
  suspend: {{ if .Values.schedule }}false{{ else }}true{{ end }}
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "tkeir-indexer.labels" . | nindent 12 }}
        spec:
          serviceAccountName: {{ include "tkeir-indexer.serviceAccountName" . }}
          restartPolicy: OnFailure
          securityContext:
            {{- include "tkeir-lib.securityContext" . | nindent 12 }}
          containers:
            - name: indexer
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args: {{ toJson .Values.command }}
              env:
                {{- range $k, $v := .Values.env }}
                {{- if $v }}
                - name: {{ $k }}
                  value: {{ $v | quote }}
                {{- end }}
                {{- end }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              volumeMounts:
                - name: data
                  mountPath: /data
          volumes:
            - name: data
              emptyDir: {}
