{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tkeir-audit.fullname" . }}-postgres
  labels:
    {{- include "tkeir-audit.labels" . | nindent 4 }}
spec:
  ports:
    - port: 5432
      name: postgres
  selector:
    app.kubernetes.io/name: {{ include "tkeir-audit.name" . }}-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tkeir-audit.fullname" . }}-postgres
  labels:
    {{- include "tkeir-audit.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "tkeir-audit.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "tkeir-audit.name" . }}-postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "tkeir-audit.name" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password | quote }}
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgres.storage }}
{{- end }}
